### ISSUE TITLE
Apply meta migrations and port makemigrations check from geniza

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/cdh-web#386]
- [ ] Create the ~10 migrations 
- [ ] To prevent these from piling up in the feature, implement an actions check (already done in [geniza](https://github.com/Princeton-CDH/geniza/blob/main/.github/workflows/unit_tests.yml))

```yaml
      - name: Ensure all migrations have been created
        if: ${{ github.event_name == 'pull_request' }}
        run: python manage.py makemigrations --check --no-input

```
